global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: prometheus

  - job_name: "argus_agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"] # if Prometheus runs on same machine as the agent
